/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'bg-indigo-100',
    'bg-indigo-500',
    'bg-indigo-50',
    'text-indigo-600',
    'border-indigo-600',
    'hover:bg-indigo-50',
    'hover:ring-indigo-200',
    'bg-emerald-100',
    'bg-emerald-500',
    'bg-emerald-50',
    'text-emerald-600',
    'border-emerald-600',
    'hover:bg-emerald-50',
    'hover:ring-emerald-200',
    'bg-amber-100',
    'bg-amber-500',
    'bg-amber-50',
    'text-amber-600',
    'border-amber-600',
    'hover:bg-amber-50',
    'hover:ring-amber-200',
    'bg-rose-100',
    'bg-rose-500',
    'bg-rose-50',
    'text-rose-600',
    'border-rose-600',
    'hover:bg-rose-50',
    'hover:ring-rose-200',
  ],
};